services:
  api:
    build: api
    restart: unless-stopped
    volumes:
      - ./api:/app
    ports:
      - 8000:8000
    depends_on:
      - database
    env_file:
      - project.env

  database:
    container_name: postgresql_todo-database
    image: postgres:16.1
    restart: unless-stopped
    env_file:
      - project.env